// Which files count as coding activity, what language they are, and how agent
// worktrees and git operations are recognised. Pure (no vscode import) so it
// is unit tested directly; ActivityTracker is the only consumer.

// Map file extensions to VS Code languageIds so external (agent/CLI) edits merge
// with stats recorded from open editors, which use document.languageId.
const EXTENSION_LANGUAGES: Record<string, string> = {
  ts: "typescript", mts: "typescript", cts: "typescript", tsx: "typescriptreact",
  js: "javascript", mjs: "javascript", cjs: "javascript", jsx: "javascriptreact",
  py: "python", rb: "ruby", go: "go", rs: "rust", java: "java",
  kt: "kotlin", kts: "kotlin", c: "c", h: "c",
  cpp: "cpp", cc: "cpp", cxx: "cpp", hpp: "cpp",
  cs: "csharp", php: "php", swift: "swift", scala: "scala",
  sh: "shellscript", bash: "shellscript", zsh: "shellscript",
  ps1: "powershell", psm1: "powershell", bat: "bat",
  sql: "sql", html: "html", htm: "html", css: "css", scss: "scss", less: "less",
  vue: "vue", svelte: "svelte", json: "json", jsonc: "jsonc",
  md: "markdown", yml: "yaml", yaml: "yaml", toml: "toml", xml: "xml",
  graphql: "graphql", gql: "graphql", dart: "dart", lua: "lua", r: "r",
  ex: "elixir", exs: "elixir", erl: "erlang", hs: "haskell",
  clj: "clojure", zig: "zig", tf: "terraform", ini: "ini",
  proto: "proto", astro: "astro", prisma: "prisma", sol: "solidity",
  cmake: "cmake", groovy: "groovy", gradle: "groovy", pl: "perl",
  m: "objective-c", mm: "objective-cpp", fs: "fsharp", nim: "nim",
  tex: "latex", env: "dotenv",
}

// Well-known files without a (meaningful) extension. Keys are lowercase.
const BASENAME_LANGUAGES: Record<string, string> = {
  dockerfile: "dockerfile", makefile: "makefile", gnumakefile: "makefile",
  rakefile: "ruby", gemfile: "ruby", vagrantfile: "ruby",
  jenkinsfile: "groovy", ".env": "dotenv",
}

export function languageForFile(basename: string): string | undefined {
  const byName = BASENAME_LANGUAGES[basename.toLowerCase()]
  if (byName) return byName
  const ext = basename.includes(".") ? basename.slice(basename.lastIndexOf(".") + 1).toLowerCase() : ""
  return EXTENSION_LANGUAGES[ext]
}

// Directory segments whose contents never count as coding activity.
const EXCLUDED_SEGMENTS = new Set([
  ".git", "node_modules", "dist", "out", "build", "coverage", "vendor",
  "target", "bin", "obj", "__pycache__", ".venv", "venv",
  ".next", ".nuxt", ".idea", ".vscode", ".claude", "tmp",
  // Dot-prefixed build and cache output — `out` alone missed test/.out.
  ".out", ".output", ".turbo", ".cache", ".parcel-cache", ".svelte-kit", ".vercel",
  ".vscode-test", // VS Code's test-runner download of VS Code itself
])

// Generated files that churn in bulk without representing hand/agent-written code.
const EXCLUDED_BASENAMES = new Set([
  "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "composer.lock",
  "packages.lock.json", "bun.lockb", "go.sum", "go.work.sum",
  "Cargo.lock", "poetry.lock", "Gemfile.lock", "Podfile.lock",
  "next-env.d.ts", // regenerated by every `next dev`
])

// Some tooling registers a languageId for generated files (the Go extension calls
// go.sum's language "go.sum"), so the basename check above is not enough on its own.
export const EXCLUDED_LANGUAGE_IDS = new Set(["go.sum", "go.work.sum", "log"])

// Agent worktrees checked out inside the project. A file at
// `<repo>/<marker>/<name>/<rel>` is the main project's `<repo>/<rel>` being
// worked on elsewhere, so it is credited under that path. Only these two
// layouts are recognised: Claude Code's `.claude/worktrees/` and the common
// `.worktrees/` convention. Worktrees outside the workspace are not watched.
const WORKTREE_PATTERN = /[\\/](?:\.claude[\\/]worktrees|\.worktrees)[\\/][^\\/]+(?=[\\/])/

export interface WorktreeInfo {
  root: string     // the worktree directory
  gitFile: string  // its `.git` file — gone once the worktree is removed
  mainPath: string // the same file in the main checkout
}

export function worktreeInfo(fsPath: string): WorktreeInfo | null {
  const m = WORKTREE_PATTERN.exec(fsPath)
  if (!m) return null
  const end = m.index + m[0].length
  const root = fsPath.slice(0, end)
  return { root, gitFile: root + m[0][0] + ".git", mainPath: fsPath.slice(0, m.index) + fsPath.slice(end) }
}

// Judged on the path as the main project sees it: `.claude` stays excluded
// except for the worktrees inside it, and a worktree's own node_modules/dist
// is still skipped.
export function isExcludedPath(fsPath: string): boolean {
  const segments = (worktreeInfo(fsPath)?.mainPath ?? fsPath).split(/[\\/]/)
  const basename = segments[segments.length - 1]
  if (segments.some(s => EXCLUDED_SEGMENTS.has(s))) return true
  return EXCLUDED_BASENAMES.has(basename) || basename.includes(".min.")
}

export function isGitPath(posixPath: string): boolean {
  return posixPath.split("/").includes(".git")
}

// Files whose change means a history-moving operation (checkout, merge, pull,
// rebase, reset, cherry-pick, revert) is rewriting the working tree — of the
// main checkout (`.git/HEAD`) or of a linked worktree (`.git/worktrees/<n>/HEAD`).
// Deliberately NOT index/logs/refs: plain commits touch those, and agents that
// auto-commit after every edit (Aider) would suppress their own work. Note
// .git/logs/HEAD shares the HEAD basename, hence the exact-depth checks.
const GIT_OP_FILES = new Set(["HEAD", "ORIG_HEAD", "MERGE_HEAD", "CHERRY_PICK_HEAD", "REVERT_HEAD"])

export function isGitOpSignal(posixPath: string): boolean {
  const s = posixPath.split("/")
  const i = s.indexOf(".git")
  if (i < 0 || !GIT_OP_FILES.has(s[s.length - 1])) return false
  if (i === s.length - 2) return true
  return i === s.length - 4 && s[i + 1] === "worktrees"
}

// One spelling per file for the morning store: git reports "/" paths
// ("C:/Users/…"), VS Code reports fsPath ("c:\Users\…"). Case-folded where the
// file system is usually case-insensitive.
export function normalizePath(p: string, platform: string = process.platform): string {
  let s = p.replace(/\\/g, "/")
  if (/^[A-Za-z]:/.test(s)) s = s[0].toLowerCase() + s.slice(1)
  if (s.length > 1 && s.endsWith("/") && !/^[a-z]:\/$/.test(s)) s = s.replace(/\/+$/, "")
  return platform === "win32" || platform === "darwin" ? s.toLowerCase() : s
}

export function isUnder(p: string, root: string, platform: string = process.platform): boolean {
  const r = normalizePath(root, platform)
  return normalizePath(p, platform).startsWith(r.endsWith("/") ? r : r + "/")
}

